package com.alqude.edu.ArchiveSystem.service;

import com.alqude.edu.ArchiveSystem.dto.report.DepartmentSubmissionReport;
import com.alqude.edu.ArchiveSystem.dto.report.ProfessorSubmissionSummary;
import com.itextpdf.kernel.colors.ColorConstants;
import com.itextpdf.kernel.colors.DeviceRgb;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.element.Cell;
import com.itextpdf.layout.element.Paragraph;
import com.itextpdf.layout.element.Table;
import com.itextpdf.layout.properties.TextAlignment;
import com.itextpdf.layout.properties.UnitValue;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;
import java.time.format.DateTimeFormatter;
import java.util.LinkedHashSet;
import java.util.Set;

@Service
@RequiredArgsConstructor
@Slf4j
public class PdfReportService {
    
    private static final DateTimeFormatter DATE_FORMATTER = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");
    private static final DateTimeFormatter DATE_ONLY_FORMATTER = DateTimeFormatter.ofPattern("yyyy-MM-dd");
    
    /**
     * Generate PDF report for department submission summary
     */
    public byte[] generateDepartmentSubmissionReportPdf(DepartmentSubmissionReport report) {
        log.info("Generating PDF report for department: {}", report.getDepartmentName());
        
        try (ByteArrayOutputStream baos = new ByteArrayOutputStream()) {
            PdfWriter writer = new PdfWriter(baos);
            PdfDocument pdfDoc = new PdfDocument(writer);
            Document document = new Document(pdfDoc);
            
            // Add header
            addHeader(document, report);
            
            // Add overall statistics
            addOverallStatistics(document, report);
            
            // Add professor summaries table
            addProfessorSummariesTable(document, report);
            
            // Add footer
            addFooter(document);
            
            document.close();
            
            log.info("PDF report generated successfully");
            return baos.toByteArray();
            
        } catch (Exception e) {
            log.error("Error generating PDF report", e);
            throw new RuntimeException("Failed to generate PDF report", e);
        }
    }
    
    private void addHeader(Document document, DepartmentSubmissionReport report) {
        // Title
        Paragraph title = new Paragraph("Professor Submission Report")
                .setFontSize(20)
                .setBold()
                .setTextAlignment(TextAlignment.CENTER)
                .setMarginBottom(10);
        document.add(title);
        
        // Department name
        Paragraph dept = new Paragraph(report.getDepartmentName())
                .setFontSize(16)
                .setTextAlignment(TextAlignment.CENTER)
                .setMarginBottom(5);
        document.add(dept);
        
        // Generated info
        Paragraph info = new Paragraph(String.format("Generated by: %s | Date: %s", 
                report.getGeneratedBy(), 
                report.getGeneratedAt().format(DATE_FORMATTER)))
                .setFontSize(10)
                .setTextAlignment(TextAlignment.CENTER)
                .setMarginBottom(20)
                .setFontColor(ColorConstants.GRAY);
        document.add(info);
    }
    
    private void addOverallStatistics(Document document, DepartmentSubmissionReport report) {
        // Section title
        Paragraph sectionTitle = new Paragraph("Overall Statistics")
                .setFontSize(14)
                .setBold()
                .setMarginBottom(10);
        document.add(sectionTitle);
        
        // Statistics table
        Table statsTable = new Table(UnitValue.createPercentArray(new float[]{1, 1, 1, 1}))
                .setWidth(UnitValue.createPercentValue(100))
                .setMarginBottom(20);
        
        // Header row
        DeviceRgb headerColor = new DeviceRgb(59, 130, 246); // Blue
        addStatCell(statsTable, "Total Professors", String.valueOf(report.getTotalProfessors()), headerColor);
        addStatCell(statsTable, "Total Requests", String.valueOf(report.getTotalRequests()), headerColor);
        addStatCell(statsTable, "Submitted", String.valueOf(report.getTotalSubmitted()), new DeviceRgb(34, 197, 94)); // Green
        addStatCell(statsTable, "Pending", String.valueOf(report.getTotalPending()), new DeviceRgb(234, 179, 8)); // Yellow
        
        // Second row
        addStatCell(statsTable, "Overdue", String.valueOf(report.getTotalOverdue()), new DeviceRgb(239, 68, 68)); // Red
        addStatCell(statsTable, "Completion Rate", String.format("%.1f%%", report.getOverallCompletionRate()), headerColor);
        addStatCell(statsTable, "On-Time Rate", String.format("%.1f%%", report.getOverallOnTimeRate()), new DeviceRgb(34, 197, 94));
        addStatCell(statsTable, "", "", new DeviceRgb(255, 255, 255)); // White
        
        document.add(statsTable);
    }
    
    private void addStatCell(Table table, String label, String value, DeviceRgb color) {
        Cell cell = new Cell()
                .add(new Paragraph(label).setFontSize(9).setBold().setFontColor(ColorConstants.WHITE))
                .add(new Paragraph(value).setFontSize(14).setBold().setFontColor(ColorConstants.WHITE))
                .setBackgroundColor(color)
                .setTextAlignment(TextAlignment.CENTER)
                .setPadding(10);
        table.addCell(cell);
    }
    
    private void addProfessorSummariesTable(Document document, DepartmentSubmissionReport report) {
        // Section title
        Paragraph sectionTitle = new Paragraph("Professor Submission Details")
                .setFontSize(14)
                .setBold()
                .setMarginTop(10)
                .setMarginBottom(10);
        document.add(sectionTitle);
        
        // Create table with 8 columns
        float[] columnWidths = {3f, 1.2f, 1.2f, 1.2f, 1.2f, 1.5f, 1.5f, 2f};
        Table table = new Table(UnitValue.createPercentArray(columnWidths))
                .setWidth(UnitValue.createPercentValue(100));
        
        // Header row
        DeviceRgb headerBg = new DeviceRgb(229, 231, 235); // Gray-200
        addTableHeader(table, "Professor", headerBg);
        addTableHeader(table, "Total", headerBg);
        addTableHeader(table, "Submitted", headerBg);
        addTableHeader(table, "Pending", headerBg);
        addTableHeader(table, "Overdue", headerBg);
        addTableHeader(table, "Completion", headerBg);
        addTableHeader(table, "On-Time", headerBg);
        addTableHeader(table, "Next Deadline", headerBg);
        
        // Data rows
        for (ProfessorSubmissionSummary prof : report.getProfessorSummaries()) {
            addTableCell(table, prof.getProfessorName(), false);
            addTableCell(table, String.valueOf(prof.getTotalRequests()), true);
            addTableCell(table, String.valueOf(prof.getSubmittedRequests()), true);
            addTableCell(table, String.valueOf(prof.getPendingRequests()), true);
            addTableCell(table, String.valueOf(prof.getOverdueRequests()), true);
            addTableCell(table, String.format("%.1f%%", prof.getCompletionRate()), true);
            addTableCell(table, String.format("%.1f%%", prof.getOnTimeRate()), true);
            
            String deadline = prof.getEarliestPendingDeadline() != null ? 
                    prof.getEarliestPendingDeadline().format(DATE_ONLY_FORMATTER) : "N/A";
            addTableCell(table, deadline, true);
        }
        
        document.add(table);
    }
    
    private void addTableHeader(Table table, String text, DeviceRgb bgColor) {
        Cell cell = new Cell()
                .add(new Paragraph(text).setFontSize(9).setBold())
                .setBackgroundColor(bgColor)
                .setTextAlignment(TextAlignment.CENTER)
                .setPadding(5);
        table.addHeaderCell(cell);
    }
    
    private void addTableCell(Table table, String text, boolean center) {
        Cell cell = new Cell()
                .add(new Paragraph(text).setFontSize(8))
                .setPadding(5);
        
        if (center) {
            cell.setTextAlignment(TextAlignment.CENTER);
        }
        
        table.addCell(cell);
    }
    
    private void addFooter(Document document) {
        Paragraph footer = new Paragraph("Al-Quds University - Archiving System")
                .setFontSize(8)
                .setTextAlignment(TextAlignment.CENTER)
                .setMarginTop(20)
                .setFontColor(ColorConstants.GRAY);
        document.add(footer);
    }
    
    /**
     * Generate PDF report for professor submission report (semester-based)
     */
    public byte[] generateProfessorSubmissionReportPdf(com.alqude.edu.ArchiveSystem.dto.report.ProfessorSubmissionReport report) {
        log.info("Generating PDF report for semester: {}, department: {}", 
                report.getSemesterName(), report.getDepartmentName());
        
        try (ByteArrayOutputStream baos = new ByteArrayOutputStream()) {
            PdfWriter writer = new PdfWriter(baos);
            PdfDocument pdfDoc = new PdfDocument(writer);
            Document document = new Document(pdfDoc);
            
            // Add header
            addSemesterReportHeader(document, report);
            
            // Add overall statistics
            addSemesterStatistics(document, report);
            
            // Add professor submission table
            addProfessorSubmissionTable(document, report);
            
            // Add footer
            addFooter(document);
            
            document.close();
            
            log.info("PDF report generated successfully");
            return baos.toByteArray();
            
        } catch (Exception e) {
            log.error("Error generating PDF report", e);
            throw new RuntimeException("Failed to generate PDF report", e);
        }
    }
    
    private void addSemesterReportHeader(Document document, com.alqude.edu.ArchiveSystem.dto.report.ProfessorSubmissionReport report) {
        // Title
        Paragraph title = new Paragraph("Professor Submission Report")
                .setFontSize(20)
                .setBold()
                .setTextAlignment(TextAlignment.CENTER)
                .setMarginBottom(10);
        document.add(title);
        
        // Semester and Department
        Paragraph info = new Paragraph(String.format("%s - %s", 
                report.getSemesterName(), report.getDepartmentName()))
                .setFontSize(16)
                .setTextAlignment(TextAlignment.CENTER)
                .setMarginBottom(5);
        document.add(info);
        
        // Generated info
        Paragraph generated = new Paragraph(String.format("Generated by: %s | Date: %s", 
                report.getGeneratedBy(), 
                report.getGeneratedAt().format(DATE_FORMATTER)))
                .setFontSize(10)
                .setTextAlignment(TextAlignment.CENTER)
                .setMarginBottom(20)
                .setFontColor(ColorConstants.GRAY);
        document.add(generated);
    }
    
    private void addSemesterStatistics(Document document, com.alqude.edu.ArchiveSystem.dto.report.ProfessorSubmissionReport report) {
        // Section title
        Paragraph sectionTitle = new Paragraph("Overall Statistics")
                .setFontSize(14)
                .setBold()
                .setMarginBottom(10);
        document.add(sectionTitle);
        
        com.alqude.edu.ArchiveSystem.dto.report.SubmissionStatistics stats = report.getStatistics();
        
        // Statistics table
        Table statsTable = new Table(UnitValue.createPercentArray(new float[]{1, 1, 1, 1}))
                .setWidth(UnitValue.createPercentValue(100))
                .setMarginBottom(20);
        
        // First row
        DeviceRgb headerColor = new DeviceRgb(59, 130, 246); // Blue
        addStatCell(statsTable, "Total Professors", String.valueOf(stats.getTotalProfessors()), headerColor);
        addStatCell(statsTable, "Total Courses", String.valueOf(stats.getTotalCourses()), headerColor);
        addStatCell(statsTable, "Required Documents", String.valueOf(stats.getTotalRequiredDocuments()), headerColor);
        addStatCell(statsTable, "Submitted", String.valueOf(stats.getSubmittedDocuments()), new DeviceRgb(34, 197, 94)); // Green
        
        // Second row
        addStatCell(statsTable, "Missing", String.valueOf(stats.getMissingDocuments()), new DeviceRgb(234, 179, 8)); // Yellow
        addStatCell(statsTable, "Overdue", String.valueOf(stats.getOverdueDocuments()), new DeviceRgb(239, 68, 68)); // Red
        
        double completionRate = stats.getTotalRequiredDocuments() > 0 ? 
                (double) stats.getSubmittedDocuments() / stats.getTotalRequiredDocuments() * 100 : 0.0;
        addStatCell(statsTable, "Completion Rate", String.format("%.1f%%", completionRate), headerColor);
        addStatCell(statsTable, "", "", new DeviceRgb(255, 255, 255)); // White
        
        document.add(statsTable);
    }
    
    private void addProfessorSubmissionTable(Document document, com.alqude.edu.ArchiveSystem.dto.report.ProfessorSubmissionReport report) {
        // Section title
        Paragraph sectionTitle = new Paragraph("Submission Details by Course")
                .setFontSize(14)
                .setBold()
                .setMarginTop(10)
                .setMarginBottom(10);
        document.add(sectionTitle);
        
        if (report.getRows().isEmpty()) {
            document.add(new Paragraph("No data available").setFontSize(10).setFontColor(ColorConstants.GRAY));
            return;
        }
        
        // Determine document types present in the report
        Set<com.alqude.edu.ArchiveSystem.entity.DocumentTypeEnum> documentTypes = new LinkedHashSet<>();
        for (com.alqude.edu.ArchiveSystem.dto.report.ProfessorSubmissionRow row : report.getRows()) {
            documentTypes.addAll(row.getDocumentStatuses().keySet());
        }
        
        // Create table with dynamic columns: Professor, Course, and one column per document type
        int columnCount = 2 + documentTypes.size();
        float[] columnWidths = new float[columnCount];
        columnWidths[0] = 3f; // Professor
        columnWidths[1] = 2f; // Course
        for (int i = 2; i < columnCount; i++) {
            columnWidths[i] = 1.5f; // Document type columns
        }
        
        Table table = new Table(UnitValue.createPercentArray(columnWidths))
                .setWidth(UnitValue.createPercentValue(100));
        
        // Header row
        DeviceRgb headerBg = new DeviceRgb(229, 231, 235); // Gray-200
        addTableHeader(table, "Professor", headerBg);
        addTableHeader(table, "Course", headerBg);
        for (com.alqude.edu.ArchiveSystem.entity.DocumentTypeEnum docType : documentTypes) {
            addTableHeader(table, docType.name(), headerBg);
        }
        
        // Data rows
        for (com.alqude.edu.ArchiveSystem.dto.report.ProfessorSubmissionRow row : report.getRows()) {
            addTableCell(table, row.getProfessorName(), false);
            addTableCell(table, row.getCourseCode(), false);
            
            for (com.alqude.edu.ArchiveSystem.entity.DocumentTypeEnum docType : documentTypes) {
                com.alqude.edu.ArchiveSystem.dto.report.DocumentStatusInfo statusInfo = 
                        row.getDocumentStatuses().get(docType);
                com.alqude.edu.ArchiveSystem.entity.SubmissionStatus status = 
                        statusInfo != null ? statusInfo.getStatus() : com.alqude.edu.ArchiveSystem.entity.SubmissionStatus.NOT_UPLOADED;
                addStatusCell(table, status);
            }
        }
        
        document.add(table);
        
        // Add legend
        addStatusLegend(document);
    }
    
    private void addStatusCell(Table table, com.alqude.edu.ArchiveSystem.entity.SubmissionStatus status) {
        String text;
        DeviceRgb color;
        
        switch (status) {
            case UPLOADED:
                text = "✓";
                color = new DeviceRgb(34, 197, 94); // Green
                break;
            case OVERDUE:
                text = "✗";
                color = new DeviceRgb(239, 68, 68); // Red
                break;
            case NOT_UPLOADED:
            default:
                text = "○";
                color = new DeviceRgb(156, 163, 175); // Gray
                break;
        }
        
        Cell cell = new Cell()
                .add(new Paragraph(text).setFontSize(12).setBold().setFontColor(color))
                .setTextAlignment(TextAlignment.CENTER)
                .setPadding(5);
        
        table.addCell(cell);
    }
    
    private void addStatusLegend(Document document) {
        Paragraph legend = new Paragraph()
                .setFontSize(8)
                .setMarginTop(10)
                .setFontColor(ColorConstants.GRAY);
        
        legend.add("Legend: ");
        legend.add(new Paragraph("✓ = Uploaded").setFontColor(new DeviceRgb(34, 197, 94)));
        legend.add(" | ");
        legend.add(new Paragraph("○ = Not Uploaded").setFontColor(new DeviceRgb(156, 163, 175)));
        legend.add(" | ");
        legend.add(new Paragraph("✗ = Overdue").setFontColor(new DeviceRgb(239, 68, 68)));
        
        document.add(legend);
    }
}
